Name:           ros-melodic-urg-node
Version:        0.1.11
Release:        0%{?dist}
Summary:        ROS urg_node package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/urg_node
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-diagnostic-updater
Requires:       ros-melodic-dynamic-reconfigure
Requires:       ros-melodic-laser-proc
Requires:       ros-melodic-message-generation
Requires:       ros-melodic-message-runtime
Requires:       ros-melodic-nodelet
Requires:       ros-melodic-rosconsole
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-std-srvs
Requires:       ros-melodic-tf
Requires:       ros-melodic-urg-c
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-diagnostic-updater
BuildRequires:  ros-melodic-dynamic-reconfigure
BuildRequires:  ros-melodic-laser-proc
BuildRequires:  ros-melodic-message-generation
BuildRequires:  ros-melodic-nodelet
BuildRequires:  ros-melodic-rosconsole
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-roslaunch
BuildRequires:  ros-melodic-roslint
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-std-srvs
BuildRequires:  ros-melodic-tf
BuildRequires:  ros-melodic-urg-c

%description
urg_node

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Aug 17 2018 Tony Baltovski <tony.baltovski@gmail.com> - 0.1.11-0
- Autogenerated by Bloom

