Name:           ros-jade-urg-node
Version:        0.1.11
Release:        0%{?dist}
Summary:        ROS urg_node package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/urg_node
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-diagnostic-updater
Requires:       ros-jade-dynamic-reconfigure
Requires:       ros-jade-laser-proc
Requires:       ros-jade-message-generation
Requires:       ros-jade-message-runtime
Requires:       ros-jade-nodelet
Requires:       ros-jade-rosconsole
Requires:       ros-jade-roscpp
Requires:       ros-jade-sensor-msgs
Requires:       ros-jade-std-msgs
Requires:       ros-jade-std-srvs
Requires:       ros-jade-tf
Requires:       ros-jade-urg-c
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-diagnostic-updater
BuildRequires:  ros-jade-dynamic-reconfigure
BuildRequires:  ros-jade-laser-proc
BuildRequires:  ros-jade-message-generation
BuildRequires:  ros-jade-nodelet
BuildRequires:  ros-jade-rosconsole
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-roslaunch
BuildRequires:  ros-jade-roslint
BuildRequires:  ros-jade-sensor-msgs
BuildRequires:  ros-jade-std-msgs
BuildRequires:  ros-jade-std-srvs
BuildRequires:  ros-jade-tf
BuildRequires:  ros-jade-urg-c

%description
urg_node

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Tue Oct 17 2017 Tony Baltovski <tony.baltovski@gmail.com> - 0.1.11-0
- Autogenerated by Bloom

* Tue Mar 21 2017 Tony Baltovski <tony.baltovski@gmail.com> - 0.1.10-0
- Autogenerated by Bloom

* Wed Apr 22 2015 Chad Rockey <chadrockey@gmail.com> - 0.1.9-0
- Autogenerated by Bloom

